name: Repository Insights and Analytics

on:
  schedule:
    # Run daily at midnight
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  insights:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Generate Repository Insights
      uses: lowlighter/metrics@latest
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        output_action: pull-request
        filename: insights.svg
        template: classic
        base: ""
        config_display: large
        config_timezone: UTC
        
        # Core metrics
        plugin_lines: yes
        plugin_lines_repositories_limit: 4
        
        # Languages metrics
        plugin_languages: yes
        plugin_languages_limit: 8
        plugin_languages_threshold: 0%
        
        # Most used languages
        plugin_languages_indepth: yes
        plugin_languages_details: bytes-size, percentage
        
        # Repositories metrics
        plugin_repositories: yes
        plugin_repositories_featured: >-
          Dishant27/linkedin-mcp-server
        
        # Contributors
        plugin_contributors: yes
        plugin_contributors_contributions: yes
        plugin_contributors_repositories: yes

    - name: Track Repository Clones
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const clones = await github.rest.repos.getClones({
            owner: context.repo.owner,
            repo: context.repo.repo
          });
          console.log('Repository Clones:', clones);

    # Optional: Send insights to Slack/Discord
    # - name: Send Insights Notification
    #   uses: 8398a7/action-slack@v3
    #   with:
    #     status: ${{ job.status }}
    #     fields: repo,message,commit,author,action,eventName,ref,workflow
    #   env:
    #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
    #   if: failure()
